"""initial db model migration

Revision ID: b5b92166a7be
Revises: 
Create Date: 2026-03-16 07:53:00.854258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b92166a7be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('year_of_founding', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_artists_year_of_founding'), ['year_of_founding'], unique=False)

    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_name'), ['name'], unique=True)

    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('discogs_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('format', sa.Enum('vinyl', 'cd', 'digital', name='format_enum'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('cover_path', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discogs_id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_title'), ['title'], unique=False)

    op.create_table('album_genres',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'genre_id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_track_number'), ['track_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_track_number'))
        batch_op.drop_index(batch_op.f('ix_tracks_title'))
        batch_op.drop_index(batch_op.f('ix_tracks_album_id'))

    op.drop_table('tracks')
    op.drop_table('album_genres')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_title'))
        batch_op.drop_index(batch_op.f('ix_albums_artist_id'))

    op.drop_table('albums')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_name'))

    op.drop_table('genres')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_year_of_founding'))
        batch_op.drop_index(batch_op.f('ix_artists_name'))

    op.drop_table('artists')
    # ### end Alembic commands ###
